[package]
name = "ads"
version = "0.4.3"
edition = "2018"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
license = "MIT/Apache-2.0"
description = "Client for the Beckhoff Automation Device Specification protocol for PLCs"
repository = "https://github.com/birkenfeld/ads-rs"
keywords = ["Beckhoff", "ADS", "automation", "device", "PLC"]

[dependencies]
byteorder = "1.4.3"
crossbeam-channel = "0.5.1"
itertools = "0.10.1"
thiserror = "=1.0.39"
zerocopy = "0.3.0"

[dev-dependencies]
parse_int = "0.6.0"
regex = "1.5.4"
structopt = "0.3.25"
strum = { version = "0.24", features = ["derive"] }
# Versions pinned for 1.48 compatibility
once_cell = "=1.14.0"
quick-xml = "0.22.0"
time = { version = "=0.3.2", features = ["formatting"] }
